### ISSUE TITLE
Automatic membership in UCB posix group

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#125] opened 2016-10-07 20:10 UTC
pruprecht [2:08 PM]  
Guys, does the account-creation process add UCB users to a "UCB" posix group that can be used to control access to site-licensed software?  If not, could we please add that feature?

**Comment by anderbubble** [comment] 2016-10-07 20:10
@pruprecht

**Comment by zebulasampedro** [comment] 2017-02-09 01:11
Duplicate of #163

**Closed** 2017-02-09 18:01 UTC
Labels: duplicate, enhancement
